$(document).ready(function () {
    
    const Quiz = [

        
            { q: "Qual time conquistou o Campeonato Brasileiro de 2001?", opts: ["Atlético Paranaense", "Corinthians", "São Caetano"], ans: "Atlético Paranaense" },
            { q: "Quem foi o artilheiro do Brasileirão 2003, primeiro da era dos pontos corridos?", opts: ["Dimba", "Romário", "Luizão"], ans: "Dimba" },
            { q: "Qual técnico venceu o Brasileirão por três clubes diferentes?", opts: ["Muricy Ramalho", "Abel Braga", "Cuca"], ans: "Muricy Ramalho" },
            { q: "Qual time teve a maior pontuação em uma edição do Brasileirão de pontos corridos (até 2024)?", opts: ["Flamengo 2019", "Cruzeiro 2014", "Corinthians 2015"], ans: "Flamengo 2019" },
            { q: "Qual foi o time rebaixado em 2023 com a pior defesa da competição?", opts: ["Santos", "América-MG", "Coritiba"], ans: "América-MG" },
            { q: "Quem foi eleito o craque do Brasileirão 2019?", opts: ["Gabigol", "Bruno Henrique", "Arrascaeta"], ans: "Gabigol" },
            { q: "Qual jogador marcou o gol do título do Corinthians em 2011?", opts: ["Liédson", "Danilo", "Paulinho"], ans: "Paulinho" },
            { q: "Qual clube foi campeão brasileiro de 2008?", opts: ["São Paulo", "Flamengo", "Internacional"], ans: "São Paulo" },
            { q: "Qual foi o último time fora do eixo Sul-Sudeste a ser campeão brasileiro?", opts: ["Sport", "Bahia", "Athletico-PR"], ans: "Athletico-PR" },
            { q: "Qual time teve o maior número de empates no Brasileirão 2022?", opts: ["São Paulo", "Corinthians", "Ceará"], ans: "São Paulo" },
            { q: "Quem foi o técnico campeão com o Palmeiras em 2022?", opts: ["Abel Ferreira", "Felipão", "Luxemburgo"], ans: "Abel Ferreira" },
            { q: "Qual time foi rebaixado pela primeira vez em sua história em 2023?", opts: ["Santos", "Vasco", "Cruzeiro"], ans: "Santos" },
            { q: "Quem foi o artilheiro do Brasileirão 2021?", opts: ["Hulk", "Gabigol", "Calleri"], ans: "Hulk" },
            { q: "Qual clube venceu o Brasileirão 2007?", opts: ["São Paulo", "Flamengo", "Cruzeiro"], ans: "São Paulo" },
            { q: "Qual jogador venceu o prêmio de revelação do Brasileirão 2020?", opts: ["Claudinho", "Patrick de Paula", "Calegari"], ans: "Claudinho" },
            { q: "Qual foi o time com o maior saldo de gols em uma edição de pontos corridos até 2024?", opts: ["Flamengo 2019", "Cruzeiro 2014", "Palmeiras 2022"], ans: "Flamengo 2019" },
            { q: "Quem foi o goleiro menos vazado do Brasileirão 2018?", opts: ["Cássio", "Weverton", "Marcelo Grohe"], ans: "Marcelo Grohe" },
            { q: "Qual foi o time que terminou o Brasileirão 2010 com a melhor defesa?", opts: ["Fluminense", "Cruzeiro", "Corinthians"], ans: "Fluminense" },
            { q: "Quem foi o artilheiro do Brasileirão 2023?", opts: ["Tiquinho Soares", "Germán Cano", "Hulk"], ans: "Tiquinho Soares" },
            { q: "Qual clube teve a pior campanha dos pontos corridos até hoje?", opts: ["América-RN 2007", "Náutico 2013", "CSA 2019"], ans: "América-RN 2007" },
            { q: "Qual foi o campeão brasileiro de 2015?", opts: ["Corinthians", "Palmeiras", "Atlético Mineiro"], ans: "Corinthians" },
            { q: "Quem foi o técnico do Cruzeiro bicampeão em 2013 e 2014?", opts: ["Marcelo Oliveira", "Mano Menezes", "Luxemburgo"], ans: "Marcelo Oliveira" },
            { q: "Qual time perdeu o título de 2009 para o Flamengo após liderar quase todo o campeonato?", opts: ["Internacional", "São Paulo", "Palmeiras"], ans: "Palmeiras" },
            { q: "Qual jogador foi o mais jovem a estrear no Brasileirão com o Palmeiras?", opts: ["Endrick", "Gabriel Jesus", "Estevão"], ans: "Endrick" },
            { q: "Quem foi o artilheiro do Brasileirão 2017?", opts: ["Jô", "Henrique Dourado", "Fred"], ans: "Jô" },
            { q: "Qual clube teve mais vitórias no Brasileirão 2020?", opts: ["Flamengo", "Internacional", "São Paulo"], ans: "Flamengo" },
            { q: "Quem foi o primeiro campeão brasileiro após a implementação do VAR?", opts: ["Flamengo", "Palmeiras", "Corinthians"], ans: "Flamengo" },
            { q: "Qual jogador mais vezes eleito para a seleção do campeonato entre 2010 e 2024?", opts: ["Arrascaeta", "Hulk", "Gabigol"], ans: "Arrascaeta" },
            { q: "Qual foi o time com o ataque mais positivo do Brasileirão 2019?", opts: ["Flamengo", "Palmeiras", "Santos"], ans: "Flamengo" },
            { q: "Qual equipe terminou o Brasileirão 2021 com a melhor defesa?", opts: ["Atlético Mineiro", "Palmeiras", "Flamengo"], ans: "Atlético Mineiro" },
        { q: "Qual seleção ganhou a Copa de 2002?", opts: ["Brasil", "Alemanha", "França"], ans: "Brasil" },
        { q: "Quem venceu a Premier League 2011-12 com gol no último minuto?", opts: ["Manchester United", "Manchester City", "Chelsea"], ans: "Manchester City" },
        { q: "Quem foi campeão da La Liga 2014-15?", opts: ["Barcelona", "Real Madrid", "Atlético"], ans: "Barcelona" },
        { q: "Qual clube venceu a Bundesliga 2020-21?", opts: ["Bayern", "Dortmund", "Leipzig"], ans: "Bayern" },
        { q: "Quem venceu a Serie A italiana 2010-11?", opts: ["Inter", "Milan", "Juventus"], ans: "AC Milan" },
        { q: "Quem venceu a Ligue 1 francesa 2012-13?", opts: ["PSG", "Lille", "Monaco"], ans: "PSG" },
        { q: "Quem venceu a Copa do Mundo de Clubes da FIFA 2012?", opts: ["Corinthians", "Chelsea", "Bayern"], ans: "Corinthians" },
        { q: "Quem marcou 50 gols pelo Real Madrid em 2014-15?", opts: ["Cristiano Ronaldo", "Bale", "Benzema"], ans: "Cristiano Ronaldo" },
        { q: "Quem venceu a Copa do Mundo de Clubes da FIFA 2019?", opts: ["Liverpool", "Flamengo", "Barcelona"], ans: "Liverpool" },
        { q: "Quem foi eleito melhor jogador da Premier League 2018-19?", opts: ["Salah", "Van Dijk", "De Bruyne"], ans: "Van Dijk" },
        { q: "Quem foi o artilheiro da Serie A 2020-21?", opts: ["Immobile", "Zlatan", "Dybala"], ans: "Immobile" },
        { q: "Quem ganhou a Bola de Ouro 2010?", opts: ["Messi", "Iniesta", "Xavi"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2011?", opts: ["Messi", "Cristiano Ronaldo", "Xavi"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2012?", opts: ["Messi", "Cristiano Ronaldo", "Robben"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2013?", opts: ["Cristiano Ronaldo", "Messi", "Franck Ribéry"], ans: "Cristiano Ronaldo" },
        { q: "Quem ganhou a Bola de Ouro 2014?", opts: ["Cristiano Ronaldo", "Messi", "Manuel Neuer"], ans: "Cristiano Ronaldo" },
        { q: "Quem ganhou a Bola de Ouro 2015?", opts: ["Messi", "Cristiano Ronaldo", "Neymar"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2016?", opts: ["Cristiano Ronaldo", "Messi", "Antoine Griezmann"], ans: "Cristiano Ronaldo" },
        { q: "Quem ganhou a Bola de Ouro 2017?", opts: ["Cristiano Ronaldo", "Messi", "Modric"], ans: "Cristiano Ronaldo" },
        { q: "Quem ganhou a Bola de Ouro 2018?", opts: ["Luka Modric", "Messi", "Cristiano Ronaldo"], ans: "Luka Modric" },
        { q: "Quem ganhou a Bola de Ouro 2019?", opts: ["Messi", "Van Dijk", "Ronaldo"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2021?", opts: ["Messi", "Lewandowski", "Jorginho"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2022?", opts: ["Messi", "Kane", "Mbappé"], ans: "Messi" },
        { q: "Quem ganhou a Bola de Ouro 2023?", opts: ["Messi", "Haaland", "Mbappé"], ans: "Messi" },
        { q: "Quem venceu a Champions League 2011?", opts: ["Barcelona", "Manchester United", "Real Madrid"], ans: "Barcelona" },
        { q: "Quem venceu a Champions League 2012?", opts: ["Chelsea", "Bayern", "Real Madrid"], ans: "Chelsea" },
        { q: "Quem venceu a Champions League 2013?", opts: ["Bayern", "Borussia Dortmund", "Real Madrid"], ans: "Bayern" },
        { q: "Quem venceu a Champions League 2014?", opts: ["Real Madrid", "Atlético de Madrid", "Barcelona"], ans: "Real Madrid" },
        { q: "Quem venceu a Champions League 2015?", opts: ["Barcelona", "Juventus", "Real Madrid"], ans: "Barcelona" },
        { q: "Quem venceu a Champions League 2016?", opts: ["Real Madrid", "Atlético de Madrid", "Bayern"], ans: "Real Madrid" },
        { q: "Quem venceu a Champions League 2017?", opts: ["Real Madrid", "Juventus", "Barcelona"], ans: "Real Madrid" },
        { q: "Quem venceu a Champions League 2018?", opts: ["Real Madrid", "Liverpool", "Bayern"], ans: "Real Madrid" },
        { q: "Quem venceu a Champions League 2019?", opts: ["Liverpool", "Tottenham", "Barcelona"], ans: "Liverpool" },
        { q: "Quem venceu a Champions League 2020?", opts: ["Bayern", "PSG", "Lyon"], ans: "Bayern" },
        { q: "Quem venceu a Champions League 2021?", opts: ["Chelsea", "Manchester City", "Real Madrid"], ans: "Chelsea" },
        { q: "Quem venceu a Champions League 2022?", opts: ["Real Madrid", "Liverpool", "Manchester City"], ans: "Real Madrid" },
        { q: "Quem venceu a Champions League 2023?", opts: ["Manchester City", "Inter", "PSG"], ans: "Manchester City" },
        { q: "Quem foi o artilheiro da Champions 2020-21?", opts: ["Lewandowski", "Messi", "Mbappé"], ans: "Lewandowski" },
        { q: "Quem foi o artilheiro da Champions 2021-22?", opts: ["Mbappé", "Lewandowski", "Haalaand"], ans: "Haalaand" },
        { q: "Quem venceu a Copa do Mundo 2010?", opts: ["Holanda", "Espanha", "Alemanha"], ans: "Espanha" },
        { q: "Quem marcou o gol da vitória da Espanha na final de 2010?", opts: ["Iniesta", "Xavi", "Villa"], ans: "Iniesta" },
        { q: "Qual seleção foi vice na Copa 2010?", opts: ["Holanda", "Alemanha", "Uruguai"], ans: "Holanda" },
        { q: "Quem venceu a Copa do Mundo 2014?", opts: ["Brasil", "Alemanha", "Argentina"], ans: "Alemanha" },
        { q: "Quem marcou o gol da final da Copa 2014?", opts: ["Müller", "Götze", "Hernández"], ans: "Götze" },
        { q: "Qual seleção foi vice na Copa 2014?", opts: ["Argentina", "Brasil", "Holanda"], ans: "Argentina" },
        { q: "Quem venceu a Copa do Mundo 2018?", opts: ["Croácia", "França", "Bélgica"], ans: "França" },
        { q: "Quem marcou na final da Copa 2018?", opts: ["Mbappé", "Griezmann", "Mandzukic"], ans: "Mandzukic" },
        { q: "Quem foi o artilheiro da Copa 2014?", opts: ["James Rodríguez", "Müller", "Ronaldo"], ans: "James Rodríguez" },
        { q: "Quem ganhou a Bola de Ouro da Copa 2018?", opts: ["Luka Modrić", "Mbappé", "Griezmann"], ans: "Luka Modrić" },
        { q: "Quem ganhou a Copa América 2015?", opts: ["Brasil", "Chile", "Argentina"], ans: "Chile" },
        { q: "Quem venceu a Copa América 2016 (Centenário)?", opts: ["Chile", "Argentina", "Brasil"], ans: "Chile" },
        { q: "Quem venceu a Copa América 2019?", opts: ["Brasil", "Argentina", "Uruguai"], ans: "Brasil" },
        { q: "Quem venceu a Copa América 2021?", opts: ["Brasil", "Argentina", "Uruguai"], ans: "Argentina" },
        { q: "Quem foi o artilheiro da Copa América 2019?", opts: ["Everton Cebolinha", "Gabriel Jesus", "Agüero"], ans: "Everton Cebolinha" },                      
        { q: "Onde foi a Copa 2014?", opts: ["Brasil", "África do Sul", "Rússia"], ans: "Brasil" },
        { q: "Qual clube é conhecido como 'Reds'?", opts: ["Chelsea", "Liverpool", "Arsenal"], ans: "Liverpool" },
        { q: "Quantas Copas o Brasil tem?", opts: ["4", "5", "6"], ans: "5" },
        { q: "Quem é o 'Fenômeno'?", opts: ["Cristiano Ronaldo", "Ronaldo Nazário", "Ronaldinho"], ans: "Ronaldo Nazário" },
        { q: "Qual seleção tem mais Copas?", opts: ["Brasil", "Alemanha", "Itália"], ans: "Brasil" },
        { q: "Qual clube brasileiro é conhecido como 'Mengão'?", opts: ["Fluminense", "Flamengo", "Vasco"], ans: "Flamengo" },
        { q: "Qual é o apelido do Santos?", opts: ["Peixe", "Galo", "Timão"], ans: "Peixe" },
        { q: "Quem ganhou a Copa de 1998?", opts: ["Brasil", "França", "Alemanha"], ans: "França" },
        { q: "Quem marcou os gols da final de 2002?", opts: ["Ronaldinho", "Rivaldo", "Ronaldo Fenômeno"], ans: "Ronaldo Fenômeno" },
        { q: "Quem venceu a Copa América 2019?", opts: ["Brasil", "Argentina", "Chile"], ans: "Brasil" },
        { q: "Qual time é conhecido como 'Timão'?", opts: ["Corinthians", "Palmeiras", "Santos"], ans: "Corinthians" },
        { q: "Maior artilheiro da Copa de 2006?", opts: ["Klose", "Ronaldo", "Messi"], ans: "Klose" },
        { q: "Qual time tem mais títulos brasileiros?", opts: ["Palmeiras", "São Paulo", "Flamengo"], ans: "Palmeiras" },
        { q: "Quem é conhecido como 'O Mágico'?", opts: ["Ronaldinho", "Messi", "Neymar"], ans: "Ronaldinho" },
        { q: "Qual seleção venceu a Copa 2018?", opts: ["França", "Croácia", "Brasil"], ans: "França" },
        { q: "Quem é o maior artilheiro da história do Brasileirão?", opts: ["Roberto Dinamite", "Pelé", "Zico"], ans: "Roberto Dinamite" },
        { q: "Qual clube é conhecido como 'Galo'?", opts: ["Atlético-MG", "Cruzeiro", "Flamengo"], ans: "Atlético-MG" },
        { q: "Qual jogador nunca jogou no Barcelona?", opts: ["Coutinho", "Eto'o", "Nico Williams"], ans: "Nico Williams" },
        { q: "Qual seleção venceu a Copa de 1958?", opts: ["Brasil", "Suécia", "Alemanha"], ans: "Brasil" },
        { q: "Quantas Champions o Barcelona tem?", opts: ["4", "5", "6"], ans: "5" },
        { q: "Quem ganhou a Bola de Ouro 2023?", opts: ["Messi", "Haaland", "Mbappé"], ans: "Messi" },
        { q: "Maior artilheiro da Champions League?", opts: ["Cristiano Ronaldo", "Messi", "Benzema"], ans: "Cristiano Ronaldo" },
        { q: "Qual time tem mais Libertadores?", opts: ["Inter", "Corinthias", "Flamengo"], ans: "São Paulo" },
        { q: "Quem foi campeão da Copa América 2021?", opts: ["Brasil", "Argentina", "Uruguai"], ans: "Argentina" },
        { q: "Qual seleção sediou a Copa de 2010?", opts: ["África do Sul", "Alemanha", "Japão"], ans: "África do Sul" },
        { q: "Qual clube tem o apelido 'Blaugrana'?", opts: ["Real Madrid", "Barcelona", "Valencia"], ans: "Barcelona" },
        { q: "Quem marcou o gol da final da Copa 2014?", opts: ["Neymar", "Mario Götze", "James Rodríguez"], ans: "Mario Götze" },
        { q: "Quem ganhou a Champions League 2023?", opts: ["Real Madrid", "Man City", "PSG"], ans: "PSG" },
        { q: "Qual jogador é chamado de 'La Pulga'?", opts: ["Messi", "Maradona", "Di María"], ans: "Messi" },
        { q: "Quem venceu a Copa América 2015?", opts: ["Chile", "Argentina", "Brasil"], ans: "Chile" },
        { q: "Qual foi o campeão da Euro 2016?", opts: ["Portugal", "França", "Alemanha"], ans: "Portugal" },
        { q: "Qual clube revelou Neymar?", opts: ["Santos", "Barcelona", "PSG"], ans: "Santos" },
        { q: "Qual jogador nunca jogou no Real Madrid?", opts: ["Benzema", "Cristiano Ronaldo", "Messi"], ans: "Messi" },
        { q: "Quem ganhou a Copa de 1994?", opts: ["Brasil", "Itália", "Alemanha"], ans: "Brasil" },
        { q: "Qual seleção venceu a Copa de 1930?", opts: ["Uruguai", "Argentina", "Brasil"], ans: "Uruguai" },
        { q: "Quem foi campeão da Copa do Mundo de 1986?", opts: ["Argentina", "Alemanha", "Brasil"], ans: "Argentina" },
        { q: "Quem é o maior artilheiro da Copa América?", opts: ["Messi", "Suárez", "Norberto Méndez"], ans: "Norberto Méndez" },
        { q: "Qual clube tem mais títulos na Premier League?", opts: ["Manchester United", "Chelsea", "Arsenal"], ans: "Manchester United" },
        { q: "Qual time tem mais títulos da Copa do Brasil?", opts: ["Cruzeiro", "Palmeiras", "Flamengo"], ans: "Cruzeiro" },
        { q: "Quem marcou o gol da final da Champions 2012 pelo Chelsea?", opts: ["Drogba", "Lampard", "Torres"], ans: "Drogba" },
        { q: "Qual seleção foi campeã da Euro 2004?", opts: ["Portugal", "Grécia", "França"], ans: "Grécia" },
        { q: "Qual foi o artilheiro da Copa 2006?", opts: ["Klose", "Henry", "Ronaldinho"], ans: "Klose" },
        { q: "Quem marcou 5 gols em um jogo de Champions pelo Barcelona?", opts: ["Messi", "Suárez", "Neymar"], ans: "Messi" },
        { q: "Qual técnico levou o Porto à Champions 2004?", opts: ["Mourinho", "Benítez", "Del Bosque"], ans: "Mourinho" },
        { q: "Quem foi o capitão da França em 1998?", opts: ["Deschamps", "Zidane", "Blanc"], ans: "Deschamps" },
        { q: "Qual país foi vice da Copa 1950 no Brasil?", opts: ["Argentina", "Uruguai", "Suécia"], ans: "Uruguai" },
        { q: "Em que clube Zidane encerrou a carreira?", opts: ["Juventus", "Real Madrid", "Bordeaux"], ans: "Real Madrid" },
        { q: "Qual seleção ganhou a Copa de 2002?", opts: ["Brasil", "Alemanha", "França"], ans: "Brasil" },
        { q: "Qual time é conhecido como 'Furacão'?", opts: ["Athletico-PR", "Internacional", "Bahia"], ans: "Athletico-PR" },
        { q: "Qual time é chamado de 'Peixe'?", opts: ["Santos", "Botafogo", "Vasco"], ans: "Santos" },
        { q: "Qual time paulista é chamado de 'Timão'?", opts: ["Corinthians", "São Paulo", "Santos"], ans: "Corinthians" },
        { q: "Qual clube carioca é chamado de 'Mengão'?", opts: ["Flamengo", "Vasco", "Botafogo"], ans: "Flamengo" },
        { q: "Quantas Copas do Mundo o Brasil conquistou?", opts: ["4", "5", "6"], ans: "5" },
        { q: "Qual time gaúcho é chamado de 'Tricolor Gaúcho'?", opts: ["Grêmio", "Internacional", "Juventude"], ans: "Grêmio" },
        { q: "Quem marcou o gol do título da Copa de 2002?", opts: ["Ronaldo", "Rivaldo", "Ronaldinho"], ans: "Ronaldo" },
        { q: "Qual time paulista tem como mascote um peixe?", opts: ["Santos", "São Paulo", "Palmeiras"], ans: "Santos" },
        { q: "Qual time carioca é conhecido como 'Fogão'?", opts: ["Botafogo", "Flamengo", "Fluminense"], ans: "Botafogo" },
        { q: "Quem é o maior artilheiro da história do Campeonato Brasileiro?", opts: ["Roberto Dinamite", "Romário", "Pelé"], ans: "Roberto Dinamite" },
        { q: "Qual clube do RS tem cores vermelho e branco?", opts: ["Internacional", "Grêmio", "São José"], ans: "Internacional" },
        { q: "Quem foi o camisa 10 do Brasil na Copa de 1970?", opts: ["Pelé", "Rivelino", "Jairzinho"], ans: "Pelé" },
        { q: "Qual time paulista é chamado de 'Alviverde'?", opts: ["Palmeiras", "São Paulo", "Santos"], ans: "Palmeiras" },
        { q: "Quem foi o técnico do Brasil no tetra em 1994?", opts: ["Parreira", "Felipão", "Zagallo"], ans: "Parreira" },
        { q: "Qual clube carioca é chamado de 'Tricolor das Laranjeiras'?", opts: ["Fluminense", "Flamengo", "Vasco"], ans: "Fluminense" },
        { q: "Qual time gaúcho venceu a Copa Libertadores em 2017?", opts: ["Grêmio", "Internacional", "Juventude"], ans: "Grêmio" },
        { q: "Qual time paulista venceu a Copa Libertadores em 2012?", opts: ["Corinthians", "São Paulo", "Santos"], ans: "Corinthians" },
        { q: "Qual clube paulista conquistou o Mundial de Clubes da FIFA em 2005?", opts: ["São Paulo", "Palmeiras", "Santos"], ans: "São Paulo" },
        { q: "Quem é maior rival do São Paulo?", opts: ["Corinthians", "Palmeiras", "Santos"], ans: "Corinthians" },
        { q: "Qual clube carioca venceu a Libertadores em 2019?", opts: ["Flamengo", "Vasco", "Botafogo"], ans: "Flamengo" },
        { q: "Qual jogador brasileiro é conhecido como 'O Fenômeno'?", opts: ["Romário", "Ronaldo", "Adriano"], ans: "Ronaldo" },
        { q: "Qual time do RS tem o maior estádio?", opts: ["Grêmio", "Internacional", "Caxias"], ans: "Grêmio" },
        { q: "Qual clube gaúcho é apelidado de 'Imortal Tricolor'?", opts: ["Grêmio", "Internacional", "Brasil de Pelotas"], ans: "Grêmio" },
        { q: "Quem é conhecido como 'Rei do Drible'?", opts: ["Garrincha", "Pelé", "Ronaldinho Gaúcho"], ans: "Garrincha" },
        { q: "Qual time carioca tem cores verde, branco e grená?", opts: ["Fluminense", "Vasco", "Botafogo"], ans: "Fluminense" },
        { q: "Qual time paulista venceu a Copa Libertadores em 2005, 2006 e 2007?", opts: ["São Paulo", "Santos", "Palmeiras"], ans: "São Paulo" },
        { q: "Quem marcou o 'gol do título' do Brasil na Copa América 2019?", opts: ["Gabriel Jesus", "Everton Cebolinha", "Firmino"], ans: "Gabriel Jesus" },
        { q: "Qual time paulista tem cores verde e branco?", opts: ["Palmeiras", "Santos", "São Paulo"], ans: "Palmeiras" },
        { q: "Quem foi o capitão do Brasil no tetra em 1994?", opts: ["Dunga", "Mauro Silva", "Cafu"], ans: "Dunga" },
        { q: "Qual clube revelou Lewandowski?", opts: ["Borussia Dortmund", "Lech Poznań", "Bayern"], ans: "Lech Poznań" },
        { q: "Quem marcou hat-trick na final da Copa do Mundo?", opts: ["Pelé", "Mbappe", "Messi"], ans: "Mbappe" },
        { q: "Qual clube carioca é chamado de 'Mengão'?", opts: ["Flamengo", "Vasco", "Botafogo"], ans: "Flamengo" },
        { q: "Qual time do Rio é conhecido como 'Alvinegro'?", opts: ["Botafogo", "Flamengo", "Vasco"], ans: "Botafogo" },
        { q: "Quem é maior rival do Vasco?", opts: ["Flamengo", "Botafogo", "Fluminense"], ans: "Flamengo" },
        { q: "Qual clube carioca é chamado de 'Tricolor das Laranjeiras'?", opts: ["Fluminense", "Flamengo", "Vasco"], ans: "Fluminense" },
        { q: "Qual time do Rio conquistou a Libertadores em 2019?", opts: ["Flamengo", "Vasco", "Botafogo"], ans: "Flamengo" },
        { q: "Qual clube carioca tem o mascote de um vasco da gama?", opts: ["Vasco", "Botafogo", "Fluminense"], ans: "Vasco" },
        { q: "Qual time carioca é chamado de 'Fogão'?", opts: ["Botafogo", "Flamengo", "Fluminense"], ans: "Botafogo" },
        { q: "Quem é maior rival do Fluminense?", opts: ["Flamengo", "Botafogo", "Vasco"], ans: "Flamengo" },
        { q: "Qual clube do Rio de Janeiro tem cores verde, branco e grená?", opts: ["Fluminense", "Vasco", "Botafogo"], ans: "Fluminense" },
        { q: "Qual time do Rio venceu a Copa do Brasil em 2011?", opts: ["Vasco", "Flamengo", "Botafogo"], ans: "Vasco" },
        { q: "Qual foi o artilheiro da Champions 2023?", opts: ["Haaland", "Messi", "Ronaldo"], ans: "Haaland" },
        { q: "Quem venceu a Copa do Mundo de 1970?", opts: ["Brasil", "Alemanha", "Itália"], ans: "Brasil" },
        { q: "Quem ganhou a Copa do Mundo de 1966?", opts: ["Inglaterra", "Brasil", "Alemanha"], ans: "Inglaterra" },
        { q: "Quem venceu a Copa do Mundo de 1982?", opts: ["Itália", "Brasil", "Alemanha"], ans: "Itália" },
        { q: "Qual time gaúcho é chamado de 'Colorado'?", opts: ["Internacional", "Grêmio", "Juventude"], ans: "Internacional" },
        { q: "Qual clube é conhecido como 'Tricolor Gaúcho'?", opts: ["Grêmio", "Internacional", "São José"], ans: "Grêmio" },
        { q: "Quem venceu a Copa Libertadores de 2017 no RS?", opts: ["Grêmio", "Internacional", "Juventude"], ans: "Grêmio" },
        { q: "Qual time gaúcho tem o maior estádio do RS?", opts: ["Internacional", "Grêmio", "Caxias"], ans: "Grêmio" },
        { q: "Qual time gaúcho venceu a Copa do Brasil em 1992?", opts: ["Grêmio", "Internacional", "Juventude"], ans: "Grêmio" },
        { q: "Qual clube do RS tem como cores vermelho e branco?", opts: ["Internacional", "Grêmio", "São José"], ans: "Internacional" },
        { q: "Qual time gaúcho é apelidado de 'Imortal Tricolor'?", opts: ["Grêmio", "Internacional", "Brasil de Pelotas"], ans: "Grêmio" },
        { q: "Quem é maior rival do Internacional?", opts: ["Grêmio", "Juventude", "Caxias"], ans: "Grêmio" },
        { q: "Em que ano o Internacional conquistou a Libertadores pela primeira vez?", opts: ["2006", "2010", "1980"], ans: "2006" },
        { q: "Qual time gaúcho é conhecido como por suas cores verde e branco'?", opts: ["Juventude", "São José", "Pelotas"], ans: "Juventude" },
        { q: "Qual clube carioca é chamado de 'Mengão'?", opts: ["Flamengo", "Vasco", "Botafogo"], ans: "Flamengo" },
        { q: "Quem foi campeão da Copa Libertadores 2005?", opts: ["São Paulo", "Boca Juniors", "River Plate"], ans: "São Paulo" },
        { q: "Qual jogador foi vendido por 222 milhões de euros em 2017, o maior valor já pago em uma transferência?", opts: ["Neymar", "Mbappé", "Coutinho"], ans: "Neymar" },
        { q: "Qual clube revelou Erling Haaland antes do RB Salzburg?", opts: ["Molde", "Bryne", "Rosenborg"], ans: "Bryne" },
        { q: "Quem foi o jogador mais jovem a marcar em uma final de Copa do Mundo?", opts: ["Pelé", "Mbappé", "Messi"], ans: "Pelé" },
        { q: "Qual clube teve a maior receita do mundo em 2024 segundo a Deloitte?", opts: ["Real Madrid", "Manchester City", "PSG"], ans: "Manchester City" },
       { q: "Em 2023, qual clube europeu mais investiu em contratações (valor total)?", opts: ["Chelsea", "PSG", "Manchester United"], ans: "Chelsea" },
            { q: "Quem foi o técnico campeão da Champions League 2023 pelo Manchester City?", opts: ["Guardiola", "Arteta", "Tuchel"], ans: "Guardiola" },
            { q: "Qual jogador marcou mais gols em finais de Champions League?", opts: ["Cristiano Ronaldo", "Benzema", "Messi"], ans: "Cristiano Ronaldo" },
            { q: "Qual foi o valor estimado de mercado de Kylian Mbappé em 2022, segundo o Transfermarkt?", opts: ["160M", "180M", "200M"], ans: "180M" },
            { q: "Quem venceu a Bola de Ouro 2024?", opts: ["Rodri", "Mbappé", "Messi"], ans: "Mbappé" },
            { q: "Quem foi o jogador mais caro vendido pela Premier League até 2024?", opts: ["Declan Rice", "Jack Grealish", "Enzo Fernández"], ans: "Jack Grealish" },
            { q: "Qual time eliminou o Brasil na Copa do Mundo de 2022?", opts: ["Croácia", "Bélgica", "Holanda"], ans: "Croácia" },
            { q: "Quem foi o artilheiro da Copa do Mundo de 2022?", opts: ["Mbappé", "Messi", "Giroud"], ans: "Mbappé" },
            { q: "Qual goleiro teve mais jogos sem sofrer gols na Champions League até 2024?", opts: ["Casillas", "Neuer", "Courtois"], ans: "Casillas" },
            { q: "Quem foi o primeiro técnico a vencer a Champions League com dois clubes diferentes no século XXI?", opts: ["Mourinho", "Ancelotti", "Guardiola"], ans: "Mourinho" },
            { q: "Qual foi o primeiro clube inglês a conquistar um triplete (Premier League, FA Cup e Champions League)?", opts: ["Manchester United", "Manchester City", "Liverpool"], ans: "Manchester United" },
            { q: "Qual jogador brasileiro mais jovem a estrear em Champions League?", opts: ["Endrick", "Rodrygo", "Vinícius Júnior"], ans: "Rodrygo" },
            { q: "Quem foi o artilheiro do Brasileirão 2023?", opts: ["Tiquinho Soares", "Germán Cano", "Hulk"], ans: "Tiquinho Soares" },
            { q: "Em qual ano o VAR foi introduzido oficialmente na Copa do Mundo?", opts: ["2018", "2022", "2014"], ans: "2018" },
            { q: "Qual jogador alcançou 500 gols mais rápido na carreira profissional?", opts: ["Cristiano Ronaldo", "Messi", "Lewandowski"], ans: "Messi" },
            { q: "Quem foi o técnico da seleção argentina campeã da Copa de 2022?", opts: ["Scaloni", "Sampaoli", "Bielsa"], ans: "Scaloni" },
            { q: "Qual clube venceu a Libertadores 2023?", opts: ["Fluminense", "Palmeiras", "Boca Juniors"], ans: "Fluminense" },
            { q: "Qual foi o jogador mais jovem a marcar um gol pelo Real Madrid no século XXI?", opts: ["Rodrygo", "Vinícius Júnior", "Raúl"], ans: "Rodrygo" },
            { q: "Qual clube europeu contratou Endrick em 2023?", opts: ["Real Madrid", "Chelsea", "Barcelona"], ans: "Real Madrid" },
            { q: "Quem foi o artilheiro da Euro 2020 (disputada em 2021)?", opts: ["Cristiano Ronaldo", "Kane", "Lukaku"], ans: "Cristiano Ronaldo" },
            { q: "Quem foi o capitão do Manchester City no título da Champions 2023?", opts: ["De Bruyne", "Gündogan", "Dias"], ans: "Gündogan" },
            { q: "Qual clube foi campeão do Mundial de Clubes 2022?", opts: ["Real Madrid", "Chelsea", "Palmeiras"], ans: "Real Madrid" },
            { q: "Qual técnico mais venceu Champions League até 2025?", opts: ["Ancelotti", "Guardiola", "Zidane"], ans: "Ancelotti" },
            { q: "Qual foi o time com maior posse de bola média na Copa 2022?", opts: ["Espanha", "Alemanha", "Argentina"], ans: "Espanha" },
            { q: "Quem foi eleito o melhor goleiro da Copa do Mundo 2022?", opts: ["Emiliano Martínez", "Courtois", "Lloris"], ans: "Emiliano Martínez" },
            { q: "Qual clube teve o maior valor de elenco do mundo em 2024, segundo Transfermarkt?", opts: ["Manchester City", "Real Madrid", "PSG"], ans: "Manchester City" },
                { q: "Quem foi campeão da UEFA Champions League 2021-22?", opts: ["Manchester City", "Real Madrid", "Liverpool"], ans: "Real Madrid" },
                { q: "Qual país sediou a Copa do Mundo FIFA 2022?", opts: ["Qatar", "Emirados Árabes Unidos", "Catar"], ans: "Qatar" },
                { q: "Quem venceu a UEFA Euro 2020 (disputada em 2021)?", opts: ["Itália", "Inglaterra", "França"], ans: "Itália" },
                { q: "Qual jogador foi artilheiro da Copa do Mundo 2022?", opts: ["Kylian Mbappé", "Lionel Messi", "Olivier Giroud"], ans: "Kylian Mbappé" },
                { q: "Qual clube conquistou a tríplice coroa (Liga, Copa e SuperCopa) doméstica e continental em 2023/24?", opts: ["Manchester City", "Real Madrid", "Bayern München"], ans: "Manchester City" },
                { q: "Qual país ficou em primeiro no ranking mundial da FIFA ao final de 2023?", opts: ["Brasil", "Argentina", "Bélgica"], ans: "Argentina" },
                { q: "Quem ganhou a Ballon d'Or em 2023?", opts: ["Lionel Messi", "Erling Haaland", "Kylian Mbappé"], ans: "Lionel Messi" },
                { q: "Que clube pagou recentemente mais de 100 milhões de euros por um goleador em 2022/23?", opts: ["Manchester United", "Chelsea", "Liverpool"], ans: "Chelsea" },
                { q: "Qual jogador fez mais de 40 gols em uma única temporada europeia 2022/23?", opts: ["Erling Haaland", "Robert Lewandowski", "Kylian Mbappé"], ans: "Erling Haaland" },
                { q: "Quem foi eleito melhor jogador da Copa do Mundo de 2022?", opts: ["Lionel Messi", "Kylian Mbappé", "Emiliano Martínez"], ans: "Lionel Messi" },
                { q: "Qual seleção ganhou a Copa América 2024?", opts: ["Brasil", "Argentina", "Chile"], ans: "Argentina" },
                { q: "Qual clube venceu a primeira edição da UEFA Europa Conference League (2021-22)?", opts: ["Roma", "West Ham", "Feyenoord"], ans: "Roma" },
                { q: "Em 2024, qual jogador atingiu o valor de mercado estimado mais alto do mundo segundo o Transfermarkt?", opts: ["Kylian Mbappé", "Erling Haaland", "Vinícius Júnior"], ans: "Kylian Mbappé" },
                { q: "Que clube venceu a FIFA Club World Cup em 2023?", opts: ["Manchester City", "Real Madrid", "Flamengo"], ans: "Manchester City" },
                { q: "Qual país foi eliminado na fase de grupos da Copa do Mundo 2022 mesmo tendo a melhor posse de bola média no seu grupo?", opts: ["Brasil", "Holanda", "Espanha"], ans: "Brasil" },
                { q: "Qual técnico conquistou a Champions League em 2022-23 pela primeira vez no clube que treinava?", opts: ["Pep Guardiola", "Thomas Tuchel", "Carlo Ancelotti"], ans: "Pep Guardiola" },
                { q: "Quem foi o artilheiro da Euro 2020?", opts: ["Cristiano Ronaldo", "Harry Kane", "Romelu Lukaku"], ans: "Cristiano Ronaldo" },
                { q: "Qual clube europeu teve a maior receita anual em 2023 segundo relatório da Deloitte?", opts: ["Manchester City", "Real Madrid", "Bayern München"], ans: "Manchester City" },
                { q: "Qual seleção africana chegou mais longe numa Copa do Mundo entre 2019-2024?", opts: ["Senegal", "Ghana", "Marrocos"], ans: "Marrocos" },
                { q: "Qual jogador jovem (menor de 21 anos) foi destaque e transferido por mais de 80 milhões de euros entre 2021-24?", opts: ["Jude Bellingham", "Eduardo Camavinga", "Gio Reyna"], ans: "Jude Bellingham" },
                { q: "Qual clube foi campeão da Premier League 2023-24?", opts: ["Manchester City", "Liverpool", "Arsenal"], ans: "Manchester City" },
                { q: "Em 2022-23, qual time teve o ataque mais positivo nas cinco grandes ligas europeias?", opts: ["Manchester City", "Real Madrid", "Bayern München"], ans: "Manchester City" },
                { q: "Quem marcou o gol do título da Copa do Mundo 2022 na prorrogação/penalty?", opts: ["Lionel Messi", "Ángel Di María", "Kylian Mbappé"], ans: "Lionel Messi" },
                { q: "Qual competição UEFA teve seu regulamento alterado em 2021 para aumentar o número de participantes grupais?", opts: ["UEFA Champions League", "UEFA Europa League", "UEFA Conference League"], ans: "UEFA Champions League" },
                { q: "Qual país venceu a UEFA Women’s Championship 2022?", opts: ["Inglaterra", "Alemanha", "França"], ans: "Inglaterra" },
                { q: "Quem foi eleito o melhor jogador da Copa das Confederações ou Mundial de Clubes 2022?", opts: ["Karim Benzema", "Vinícius Júnior", "Jude Bellingham"], ans: "Vinícius Júnior" },
                { q: "Qual seleção alcançou as semifinais da Copa do Mundo 2022 sendo considerada azarão absoluto?", opts: ["Croácia", "Marrocos", "Japão"], ans: "Marrocos" },
                { q: "Qual clube detém o recorde de mais assistências numa única temporada da Champions League 2022-23?", opts: ["Real Madrid", "Manchester City", "Liverpool"], ans: "Manchester City" },
                { q: "Qual jogador se tornou o mais jovem a atingir 100 jogos pela seleção nacional entre 2019-24?", opts: ["Kylian Mbappé", "Vinícius Júnior", "Jude Bellingham"], ans: "Kylian Mbappé" },
                { q: "Qual clube da América do Sul venceu mais títulos continentais entre 2019-24?", opts: ["Palmeiras", "Flamengo", "River Plate"], ans: "Palmeiras" },
                { q: "Quem foi o técnico campeão da Copa América 2024?", opts: ["Tite", "Lionel Scaloni", "Jorge Sampaoli"], ans: "Lionel Scaloni" },
                { q: "Qual seleção europeia nunca havia chegado a uma final de Euro antes de 2020 e alcançou a em 2021?", opts: ["Inglaterra", "Croácia", "Suíça"], ans: "Inglaterra" },
                { q: "Qual clube foi campeão da La Liga 2022-23 com o menor número de derrotas nas grandes ligas europeias?", opts: ["Barcelona", "Real Madrid", "Atlético de Madrid"], ans: "Barcelona" },
                { q: "Qual jogador brasileiro venceu a Champions League entre 2019-24 mais vezes?", opts: ["Alisson Becker", "Ederson", "Vitinho"], ans: "Alisson Becker" },
                { q: "Qual foi o valor estimado da transferência de Jude Bellingham para o Real Madrid em 2023?", opts: ["100 M€", "110 M€", "130 M€"], ans: "130 M€" },
                { q: "Que clube conquistou a Bundesliga 2021-22 com 71 pontos e saldo de gols superior a +60?", opts: ["Bayern München", "Borussia Dortmund", "RB Leipzig"], ans: "Bayern München" },
                { q: "Qual foi a copa que teve mais gols na história até 2022 (incluindo finais)?", opts: ["Copa do Mundo 2022", "Copa do Mundo 2018", "Copa do Mundo 2014"], ans: "Copa do Mundo 2022" },
                { q: "Quem teve a defesa menos vazada da Premier League 2023-24?", opts: ["Arsenal", "Manchester City", "Liverpool"], ans: "Arsenal" },
                { q: "Qual jogador ganhou o prêmio de melhor jovem da Champions League 2021-22?", opts: ["Jude Bellingham", "Pedri", "Bukayo Saka"], ans: "Jude Bellingham" },
                { q: "Qual país organizou a Copa das Confederações 2021 (post-posta) ou outro torneio equivalente?", opts: ["Brasil", "Qatar", "EUA"], ans: "Qatar" },
                { q: "Qual clube francês entre 2019-24 enviou mais jogadores para a seleção campeã da Europa/ Mundial?", opts: ["Paris Saint-Germain", "Lille", "Monaco"], ans: "Paris Saint-Germain" },
                { q: "Quem marcou o gol 1000 do Real Madrid em competição europeia (aproximado entre 2019-24)?", opts: ["Karim Benzema", "Luka Modric", "Vinícius Júnior"], ans: "Vinícius Júnior" },
                { q: "Qual clube sede da final da Champions League 2022-23 recebeu mais de 90.000 espectadores?", opts: ["Atatürk Olympic Stadium", "Wembley Stadium", "Allianz Arena"], ans: "Atatürk Olympic Stadium" },
                { q: "Qual jogador se tornou o recordista de assistências numa única edição da Copa do Mundo de 2022?", opts: ["Lionel Messi", "Antoine Griezmann", "Kylian Mbappé"], ans: "Lionel Messi" },
                { q: "Qual seleção da Oceania entrou pela 1ª vez em uma Copa do Mundo entre 2019-24?", opts: ["Nova Zelândia", "Samoa", "Fiji"], ans: "Samoa" },
                { q: "Qual jogador foi o mais jovem (menos de 20 anos) a marcar no torneio de edição 2023-24 da - Champions League?", opts: ["Endrick", "Jamal Musiola", "Gavi"], ans: "Endrick" },
                { q: "Quem venceu a final da Europa League 2023-24?", opts: ["Atletico Madrid", "Roma", "Inter Milão"], ans: "Roma" },
                { q: "Qual clube ganhou o Campeonato Italiano 2022-23 com mais de 90 pontos?", opts: ["Napoli", "Juventus", "Inter Milão"], ans: "Napoli" },
                { q: "Quem foi eleito o melhor jogador jovem da Copa do Mundo 2022?", opts: ["Youssoufa Moukoko", "Jude Bellingham", "Gavi"], ans: "Youssoufa Moukoko" },
                { q: "Qual seleção asiática alcançou as oitavas de final da Copa de 2022 pela 1ª vez desde 2010?", opts: ["Coreia do Sul", "Japão", "Irã"], ans: "Japão" },
                { q: "Qual clube inglês teve mais vitórias consecutivas entre 2021-24 na Premier League?", opts: ["Liverpool", "Manchester City", "Arsenal"], ans: "Manchester City" },
                { q: "Qual jogador atingiu 50 golas ou mais numa temporada 2023-24 em La Liga?", opts: ["Karim Benzema", "Robert Lewandowski", "Vinícius Júnior"], ans: "Vinícius Júnior" },
                { q: "Em 2024, qual país anunciou oficialmente sua candidatura para sediar a FIFA World Cup 2030 em conjunto com outros?", opts: ["Espanha–Portugal", "Uruguai–Argentina–Paraguai", "Marrocos–Portugal"], ans: "Uruguai–Argentina–Paraguai" },
                    { q: "Qual clube venceu a Champions League de 2023?", opts: ["Manchester City", "Real Madrid", "Inter de Milão"], ans: "Manchester City" },
                    { q: "Quem foi o artilheiro da Champions League 2023/24?", opts: ["Haaland", "Mbappé", "Harry Kane"], ans: "Harry Kane" },
                    { q: "Qual time eliminou o Real Madrid na semifinal da Champions 2023?", opts: ["Manchester City", "PSG", "Chelsea"], ans: "Manchester City" },
                    { q: "Qual clube venceu o Mundial de Clubes da FIFA em 2022?", opts: ["Real Madrid", "Chelsea", "Palmeiras"], ans: "Real Madrid" },
                    { q: "Qual jogador marcou mais gols na Premier League 2022/23?", opts: ["Haaland", "Salah", "Kane"], ans: "Haaland" },
                    { q: "Qual foi o adversário do Rangers na final da Liga Europa 2022?", opts: ["Eintracht Frankfurt", "Sevilla", "Roma"], ans: "Eintracht Frankfurt" },
                    { q: "Qual seleção venceu a Copa América 2021?", opts: ["Argentina", "Brasil", "Chile"], ans: "Argentina" },
                    { q: "Quem marcou o gol do título da Copa América 2021?", opts: ["Di María", "Messi", "Lautaro Martínez"], ans: "Di María" },
                    { q: "Qual país sediou a Eurocopa 2021?", opts: ["Itália", "Inglaterra", "Vários países"], ans: "Vários países" },
                    { q: "Quem venceu a Eurocopa 2021?", opts: ["Itália", "Inglaterra", "França"], ans: "Itália" },
                    { q: "Qual jogador foi o mais caro do mundo em 2024 segundo o Transfermarkt?", opts: ["Mbappé", "Jude Bellingham", "Haaland"], ans: "Jude Bellingham" },
                    { q: "Qual clube contratou Jude Bellingham em 2023?", opts: ["Real Madrid", "Liverpool", "Manchester United"], ans: "Real Madrid" },
                    { q: "Qual técnico substituiu Jürgen Klopp no Liverpool em 2025?", opts: ["Xabi Alonso", "Steven Gerrard", "Pep Lijnders"], ans: "Xabi Alonso" },
                    { q: "Qual clube foi campeão francês em 2023/24?", opts: ["PSG", "Lille", "Monaco"], ans: "PSG" },
                    { q: "Qual clube espanhol foi rebaixado em 2024 pela primeira vez desde 1990?", opts: ["Valencia", "Celta de Vigo", "Sevilla"], ans: "Celta de Vigo" },
                    { q: "Quem venceu a Copa do Mundo de 2022?", opts: ["Argentina", "França", "Croácia"], ans: "Argentina" },
                    { q: "Quem marcou o hat-trick na final da Copa do Mundo 2022?", opts: ["Mbappé", "Messi", "Julián Álvarez"], ans: "Mbappé" },
                    { q: "Qual foi o adversário da Argentina na final da Copa do Mundo 2022?", opts: ["França", "Croácia", "Marrocos"], ans: "França" },
                    { q: "Qual seleção africana chegou mais longe na Copa de 2022?", opts: ["Marrocos", "Senegal", "Gana"], ans: "Marrocos" },
                    { q: "Quem foi eleito o melhor jogador jovem da Copa de 2022?", opts: ["Enzo Fernández", "Bellingham", "Gavi"], ans: "Enzo Fernández" },
                    { q: "Qual clube venceu a Libertadores 2023?", opts: ["Fluminense", "Palmeiras", "Boca Juniors"], ans: "Fluminense" },
                    { q: "Quem foi o técnico do Fluminense campeão da Libertadores 2023?", opts: ["Fernando Diniz", "Abel Ferreira", "Tite"], ans: "Fernando Diniz" },
                    { q: "Qual foi o estádio da final da Libertadores 2023?", opts: ["Maracanã", "Monumental", "Centenário"], ans: "Maracanã" },
                    { q: "Qual jogador venceu o prêmio Puskás em 2023?", opts: ["Guilherme Madruga", "Garnacho", "Richarlison"], ans: "Guilherme Madruga" },
                    { q: "Qual foi o valor aproximado da transferência de Neymar ao Al-Hilal em 2023?", opts: ["90 milhões de euros", "70 milhões de euros", "100 milhões de euros"], ans: "90 milhões de euros" },
                    { q: "Qual time é o maior rival do Rangers da Escócia?", opts: ["Celtic", "Aberdeen", "Hearts"], ans: "Celtic" },
                    { q: "Qual equipe venceu a Conference League 2023?", opts: ["West Ham", "Fiorentina", "Roma"], ans: "West Ham" },
                    { q: "Qual clube italiano retornou à Série A em 2024?", opts: ["Parma", "Sampdoria", "Palermo"], ans: "Parma" },
                    { q: "Qual jogador marcou o gol mais rápido da Champions 2024?", opts: ["Kane", "Vinícius Jr", "Osimhen"], ans: "Vinícius Jr" },
                    { q: "Quem venceu a Bola de Ouro 2024?", opts: ["Messi", "Mbappé", "Bellingham"], ans: "Messi" },
                    { q: "Quem foi eleito melhor goleiro do mundo em 2023?", opts: ["Emiliano Martínez", "Courtois", "Alisson"], ans: "Emiliano Martínez" },
                    { q: "Qual clube da Arábia Saudita contratou Cristiano Ronaldo em 2023?", opts: ["Al Nassr", "Al Hilal", "Al Ittihad"], ans: "Al Nassr" },
                    { q: "Qual clube venceu o Brasileirão 2024?", opts: ["Palmeiras", "Botafogo", "Flamengo"], ans: "Palmeiras" },
                    { q: "Qual clube contratou Endrick em 2024?", opts: ["Real Madrid", "PSG", "Manchester City"], ans: "Real Madrid" },
                    { q: "Quem venceu a Copa do Rei 2024?", opts: ["Athletic Bilbao", "Real Madrid", "Barcelona"], ans: "Athletic Bilbao" },
                    { q: "Qual jogador marcou mais gols pela seleção argentina após Messi?", opts: ["Lautaro Martínez", "Di María", "Álvarez"], ans: "Lautaro Martínez" },
                    { q: "Qual país sediará o Mundial de Clubes de 2025?", opts: ["Estados Unidos", "Arábia Saudita", "China"], ans: "Estados Unidos" },
                    { q: "Qual seleção venceu a Nations League 2023?", opts: ["Espanha", "Croácia", "França"], ans: "Espanha" },
                    { q: "Qual técnico comandou a Inglaterra na Copa de 2022?", opts: ["Gareth Southgate", "Frank Lampard", "Eddie Howe"], ans: "Gareth Southgate" },
                    { q: "Qual time espanhol tem como mascote o morcego?", opts: ["Valencia", "Villarreal", "Sevilla"], ans: "Valencia" },
                    { q: "Qual jogador foi o mais jovem a marcar em uma final de Champions?", opts: ["Ansu Fati", "Rodrygo", "Kai Havertz"], ans: "Rodrygo" },
                    { q: "Qual time venceu o Campeonato Saudita em 2023?", opts: ["Al Ittihad", "Al Hilal", "Al Nassr"], ans: "Al Ittihad" },
                    { q: "Qual clube é conhecido como 'The Reds'?", opts: ["Liverpool", "Manchester United", "Arsenal"], ans: "Liverpool" },
                    { q: "Quem foi o técnico do Real Madrid em 2024?", opts: ["Ancelotti", "Raúl", "Zidane"], ans: "Ancelotti" },
                    { q: "Qual jogador do PSG é conhecido como 'El Fideo'?", opts: ["Di María", "Dembélé", "Vitinha"], ans: "Di María" },
                    { q: "Qual país ganhou o Mundial Feminino 2023?", opts: ["Espanha", "Inglaterra", "Suécia"], ans: "Espanha" },
                    { q: "Qual jogadora foi eleita melhor do mundo em 2023?", opts: ["Aitana Bonmatí", "Sam Kerr", "Alexia Putellas"], ans: "Aitana Bonmatí" },
                    { q: "Qual clube venceu a Libertadores Feminina 2024?", opts: ["Corinthians", "Palmeiras", "Ferroviária"], ans: "Corinthians" },
                    { q: "Quem foi o artilheiro da Série A italiana 2023/24?", opts: ["Osimhen", "Lautaro Martínez", "Vlahovic"], ans: "Lautaro Martínez" },
                    { q: "Qual time é apelidado de 'Rossoneri'?", opts: ["Milan", "Inter", "Juventus"], ans: "Milan" },
                    { q: "Quem é o maior rival do Boca Juniors?", opts: ["River Plate", "San Lorenzo", "Racing"], ans: "River Plate" },
                    { q: "Qual time inglês é conhecido como 'The Toffees'?", opts: ["Everton", "Tottenham", "Leicester"], ans: "Everton" },
                    { q: "Quem foi o jogador mais caro vendido pela La Liga em 2024?", opts: ["João Félix", "Tchouaméni", "Ansu Fati"], ans: "João Félix" },
                    { q: "Qual clube venceu a Supercopa da UEFA em 2023?", opts: ["Manchester City", "Sevilla", "Real Madrid"], ans: "Manchester City" },
                    { q: "Qual clube venceu a Copa do Mundo Sub-20 de 2023?", opts: ["Uruguai", "Itália", "Brasil"], ans: "Uruguai" },
                    { q: "Quem foi eleito o Golden Boy 2024?", opts: ["Lamine Yamal", "Bellingham", "Musiala"], ans: "Lamine Yamal" },
                    { q: "Qual seleção asiática chegou às quartas da Copa 2022?", opts: ["Japão", "Coreia do Sul", "Austrália"], ans: "Japão" },
                    { q: "Qual seleção é apelidada de 'Os Três Leões'?", opts: ["Inglaterra", "Escócia", "Irlanda"], ans: "Inglaterra" },
                    { q: "Quem foi o capitão da França na Copa 2022?", opts: ["Lloris", "Mbappé", "Varane"], ans: "Lloris" },
                    { q: "Qual estádio é casa do Borussia Dortmund?", opts: ["Signal Iduna Park", "Allianz Arena", "Veltins-Arena"], ans: "Signal Iduna Park" },
                    { q: "Qual jogador marcou o gol do título da Champions 2022?", opts: ["Vinícius Jr", "Benzema", "Modric"], ans: "Vinícius Jr" },
                    { q: "Qual país será sede da Copa do Mundo 2026?", opts: ["Canadá, EUA e México", "EUA", "México"], ans: "Canadá, EUA e México" },
                    { q: "Qual jogador é conhecido como 'Captain America'?", opts: ["Pulisic", "Reyna", "McKennie"], ans: "Pulisic" },
                    { q: "Quem foi o técnico da Alemanha na Euro 2024?", opts: ["Julian Nagelsmann", "Hansi Flick", "Thomas Tuchel"], ans: "Julian Nagelsmann" },
                    { q: "Qual time venceu a Copa da Inglaterra 2024?", opts: ["Manchester United", "Manchester City", "Liverpool"], ans: "Manchester United" },
                    { q: "Quem foi o jogador mais jovem a estrear pelo Barcelona em 2023?", opts: ["Lamine Yamal", "Gavi", "Pedri"], ans: "Lamine Yamal" },
                    { q: "Qual foi o placar da final da Copa do Mundo 2022?", opts: ["3x3 (Argentina nos pênaltis)", "4x2 Argentina", "2x2 França"], ans: "3x3 (Argentina nos pênaltis)" },
                    { q: "Qual país venceu a Copa Africana de Nações 2024?", opts: ["Costa do Marfim", "Nigéria", "Senegal"], ans: "Costa do Marfim" },
                    { q: "Quem foi eleito o melhor jogador da Copa Africana 2024?", opts: ["Adingra", "Osimhen", "Haller"], ans: "Haller" },
                    { q: "Qual time venceu a MLS Cup 2023?", opts: ["Columbus Crew", "LAFC", "Inter Miami"], ans: "Columbus Crew" },
                    { q: "Qual jogador argentino foi para o Inter Miami em 2023?", opts: ["Messi", "Di María", "Otamendi"], ans: "Messi" },
                    { q: "Qual clube contratou Lionel Messi em 2023?", opts: ["Inter Miami", "Al Hilal", "PSG"], ans: "Inter Miami" },
                    { q: "Qual clube é conhecido como 'The Old Lady'?", opts: ["Juventus", "Chelsea", "Arsenal"], ans: "Juventus" },
                    { q: "Qual foi o time campeão da Copa do Mundo Sub-17 de 2023?", opts: ["Alemanha", "França", "Brasil"], ans: "Alemanha" },
                    { q: "Qual jogador marcou mais gols pela Inglaterra até 2025?", opts: ["Harry Kane", "Rooney", "Owen"], ans: "Harry Kane" },
                    { q: "Qual país venceu o torneio olímpico de futebol em Tóquio 2021?", opts: ["Brasil", "Espanha", "França"], ans: "Brasil" },
                    { q: "Quem foi o técnico do Brasil campeão olímpico em 2021?", opts: ["André Jardine", "Tite", "Fernando Diniz"], ans: "André Jardine" },
    { q: "Qual é o estádio do Palmeiras?", opts: ["Allianz Parque", "Morumbi", "Arena Corinthians"], ans: "Allianz Parque" },
    { q: "Qual é o nome do estádio do Flamengo?", opts: ["Maracanã", "Engenhão", "São Januário"], ans: "Maracanã" },
    { q: "Qual é o estádio do Grêmio?", opts: ["Arena do Grêmio", "Beira-Rio", "Olímpico"], ans: "Arena do Grêmio" },
    { q: "Qual é o estádio do Internacional?", opts: ["Beira-Rio", "Arena do Grêmio", "Castelão"], ans: "Beira-Rio" },
    { q: "Qual é o estádio do Atlético Mineiro?", opts: ["Arena MRV", "Mineirão", "Independência"], ans: "Arena MRV" },
    { q: "Qual é o estádio do Corinthians?", opts: ["Neo Química Arena", "Morumbi", "Pacaembu"], ans: "Neo Química Arena" },
    { q: "Qual é o estádio do São Paulo FC?", opts: ["Morumbi", "Allianz Parque", "Canindé"], ans: "Morumbi" },
    { q: "Qual é o estádio do Vasco da Gama?", opts: ["São Januário", "Maracanã", "Nilton Santos"], ans: "São Januário" },
    { q: "Qual é o estádio do Botafogo?", opts: ["Nilton Santos", "Maracanã", "São Januário"], ans: "Nilton Santos" },
    { q: "Qual é o estádio do Fluminense?", opts: ["Maracanã", "São Januário", "Luso-Brasileiro"], ans: "Maracanã" },
    { q: "Qual é o mascote do Palmeiras?", opts: ["Porco", "Papagaio", "Leão"], ans: "Porco" },
    { q: "Qual é o mascote do Corinthians?", opts: ["Mosqueteiro", "Gavião", "Timãozinho"], ans: "Mosqueteiro" },
    { q: "Qual é o mascote do Flamengo?", opts: ["Urubu", "Leão", "Galo"], ans: "Urubu" },
    { q: "Qual é o mascote do Atlético Mineiro?", opts: ["Galo", "Tigre", "Pantera"], ans: "Galo" },
    { q: "Qual é o mascote do Grêmio?", opts: ["Mosqueteiro", "Gremista", "Mosqueteiro Tricolor"], ans: "Mosqueteiro" },
    { q: "Qual é o mascote do Internacional?", opts: ["Saci", "Colorado", "Mosqueteiro"], ans: "Saci" },
    { q: "Qual é o mascote do São Paulo FC?", opts: ["Santo Paulo", "Tricolor", "Leão"], ans: "Santo Paulo" },
    { q: "Qual é o mascote do Vasco da Gama?", opts: ["Almirante", "Gigante", "Vascão"], ans: "Almirante" },
    { q: "Qual é o mascote do Botafogo?", opts: ["Manequinho", "Estrela Solitária", "Fogão"], ans: "Manequinho" },
    { q: "Qual é o mascote do Fluminense?", opts: ["Guerreirinho", "Cartola", "Pó de Arroz"], ans: "Cartola" },
    { q: "Qual clube é conhecido como 'Raposa'?", opts: ["Cruzeiro", "América-MG", "Coritiba"], ans: "Cruzeiro" },
    { q: "Qual clube é conhecido como 'Coelho'?", opts: ["América-MG", "Cuiabá", "Juventude"], ans: "América-MG" },
    { q: "Qual clube é conhecido como 'Furacão'?", opts: ["Athletico-PR", "Coritiba", "Goiás"], ans: "Athletico-PR" },
    { q: "Qual clube é conhecido como 'Vovô'?", opts: ["Ceará", "Fortaleza", "Bahia"], ans: "Ceará" },
    { q: "Qual clube é conhecido como 'Leão do Pici'?", opts: ["Fortaleza", "Ceará", "Sport"], ans: "Fortaleza" },
    { q: "Qual é o estádio do Bahia?", opts: ["Arena Fonte Nova", "Barradão", "Pituaçu"], ans: "Arena Fonte Nova" },
    { q: "Qual é o estádio do Sport Recife?", opts: ["Ilha do Retiro", "Arena Pernambuco", "Arruda"], ans: "Ilha do Retiro" },
    { q: "Qual é o estádio do Ceará?", opts: ["Castelão", "Presidente Vargas", "Arena das Dunas"], ans: "Castelão" },
    { q: "Qual é o estádio do Fortaleza?", opts: ["Castelão", "Presidente Vargas", "Arena Castelão"], ans: "Castelão" },
    { q: "Qual é o estádio do Athletico-PR?", opts: ["Arena da Baixada", "Durival Britto", "Couto Pereira"], ans: "Arena da Baixada" },
    { q: "Qual é o estádio do Coritiba?", opts: ["Couto Pereira", "Arena da Baixada", "Durival Britto"], ans: "Couto Pereira" },
    { q: "Quem é o técnico do Palmeiras em 2025?", opts: ["Abel Ferreira", "Fernando Diniz", "Tite"], ans: "Abel Ferreira" },
    { q: "Quem é o técnico do Fluminense em 2025?", opts: ["Fernando Diniz", "Cuca", "Dorival Júnior"], ans: "Fernando Diniz" },
    { q: "Quem é o técnico do Flamengo em 2025?", opts: ["Tite", "Ceni", "Dorival Júnior"], ans: "Tite" },
    { q: "Quem é o técnico do Corinthians em 2025?", opts: ["António Oliveira", "Luxemburgo", "Sylvinho"], ans: "António Oliveira" },
    { q: "Quem é o técnico do Vasco em 2025?", opts: ["Rafael Paiva", "Zé Ricardo", "Ramon Díaz"], ans: "Rafael Paiva" },
    { q: "Quem é o técnico do São Paulo em 2025?", opts: ["Thiago Carpini", "Dorival Júnior", "Rogério Ceni"], ans: "Thiago Carpini" },
    { q: "Quem é o técnico do Cruzeiro em 2025?", opts: ["Fernando Seabra", "Paulo Pezzolano", "Zé Ricardo"], ans: "Fernando Seabra" },
    { q: "Qual jogador do Fluminense foi destaque na Libertadores 2023?", opts: ["Germán Cano", "Ganso", "Keno"], ans: "Germán Cano" },
    { q: "Qual jogador do Palmeiras é considerado joia e foi vendido ao Real Madrid?", opts: ["Endrick", "Luis Guilherme", "Estêvão"], ans: "Endrick" },
    { q: "Qual é o estádio do Grêmio Novorizontino?", opts: ["Jorge Ismael de Biasi", "Brinco de Ouro", "Santa Cruz"], ans: "Jorge Ismael de Biasi" },
    { q: "Qual é o estádio do Vitória?", opts: ["Barradão", "Arena Fonte Nova", "Pituaçu"], ans: "Barradão" },
    { q: "Qual é o estádio do Criciúma?", opts: ["Heriberto Hülse", "Ressacada", "Orlando Scarpelli"], ans: "Heriberto Hülse" },
    { q: "Qual é o estádio do Avaí?", opts: ["Ressacada", "Scarpelli", "Heriberto Hülse"], ans: "Ressacada" },
    { q: "Qual clube é conhecido como 'Bugre'?", opts: ["Guarani", "Ituano", "Ponte Preta"], ans: "Guarani" },
    { q: "Qual clube é conhecido como 'Macaca'?", opts: ["Ponte Preta", "Botafogo-SP", "Ituano"], ans: "Ponte Preta" },
    { q: "Qual clube é conhecido como 'Pantera'?", opts: ["Botafogo-SP", "Criciúma", "Novorizontino"], ans: "Botafogo-SP" },
    { q: "Qual é o estádio da Ponte Preta?", opts: ["Moisés Lucarelli", "Brinco de Ouro", "Jorge Ismael de Biasi"], ans: "Moisés Lucarelli" },
    { q: "Qual é o estádio do Guarani?", opts: ["Brinco de Ouro", "Moisés Lucarelli", "Santa Cruz"], ans: "Brinco de Ouro" },
    { q: "Qual clube paulista tem o apelido 'Noroeste'?", opts: ["Noroeste de Bauru", "Ituano", "Ferroviária"], ans: "Noroeste de Bauru" },
    { q: "Qual clube tem o hino que começa com 'Salve o Corinthians'?", opts: ["Corinthians", "Palmeiras", "São Paulo"], ans: "Corinthians" },
    { q: "Qual clube tem o hino que cita 'Defesa que ninguém passa'?", opts: ["Fluminense", "Botafogo", "Flamengo"], ans: "Fluminense" },
    { q: "Qual clube tem o hino que fala 'Sou Tricolor de Coração'?", opts: ["São Paulo", "Bahia", "Fluminense"], ans: "São Paulo" },
    { q: "Qual clube tem o hino que fala 'E o bicho vai pegar'?", opts: ["Santos", "Atlético-MG", "Palmeiras"], ans: "Atlético-MG" },
    { q: "Qual é o estádio do Santos FC?", opts: ["Vila Belmiro", "Pacaembu", "Morumbi"], ans: "Vila Belmiro" },
    { q: "Qual é o mascote do Santos FC?", opts: ["Baleia", "Peixão", "Tubarão"], ans: "Baleia" },
    { q: "Qual é o mascote do Cruzeiro?", opts: ["Raposão", "Lobo", "Estrela Azul"], ans: "Raposão" },
    { q: "Qual clube tem o hino com o verso 'Avante, Palestra'?", opts: ["Palmeiras", "Juventus-SP", "Portuguesa"], ans: "Palmeiras" },
    { q: "Qual é o estádio do América-MG?", opts: ["Independência", "Mineirão", "Arena MRV"], ans: "Independência" },
    { q: "Qual clube do Nordeste é conhecido como 'Tubarão'? ", opts: ["CSA", "CRB", "ABC"], ans: "CSA" },
    { q: "Qual clube nordestino é conhecido como 'Papão do Norte'?", opts: ["Paysandu", "Remo", "Sampaio Corrêa"], ans: "Paysandu" },
    { q: "Qual clube é conhecido como 'Leão Azul'?", opts: ["Remo", "Fortaleza", "Avaí"], ans: "Remo" },
    { q: "Qual é o estádio do Paysandu?", opts: ["Curuzu", "Mangueirão", "Baenão"], ans: "Curuzu" },
    { q: "Qual é o estádio do Remo?", opts: ["Baenão", "Curuzu", "Mangueirão"], ans: "Baenão" },
    { q: "Qual clube é conhecido como 'Papão do Sul'?", opts: ["Criciúma", "Avaí", "Brasil de Pelotas"], ans: "Criciúma" },
    { q: "Qual clube tem o hino com o verso 'Time de tradição'?", opts: ["Grêmio", "Internacional", "Bahia"], ans: "Bahia" },
        { q: "Qual clube é conhecido como 'Los Blancos'?", opts: ["Real Madrid", "Barcelona", "Valencia"], ans: "Real Madrid" },
        { q: "Qual é o maior rival do Borussia Dortmund?", opts: ["Bayern de Munique", "Schalke 04", "Colônia"], ans: "Schalke 04" },
        { q: "Quem é o maior artilheiro da história da Champions League?", opts: ["Cristiano Ronaldo", "Messi", "Lewandowski"], ans: "Cristiano Ronaldo" },
        { q: "Em que ano o Chelsea venceu sua primeira Champions League?", opts: ["2012", "2008", "2010"], ans: "2012" },
        { q: "Qual clube é conhecido como 'The Reds'?", opts: ["Liverpool", "Arsenal", "Manchester United"], ans: "Liverpool" },
        { q: "Qual clube tem o apelido 'I Rossoneri'?", opts: ["Milan", "Inter de Milão", "Juventus"], ans: "Milan" },
        { q: "Qual é o principal rival do Celtic na Escócia?", opts: ["Rangers", "Aberdeen", "Hearts"], ans: "Rangers" },
        { q: "Em que país está localizado o clube Ajax?", opts: ["Holanda", "Bélgica", "Alemanha"], ans: "Holanda" },
        { q: "Qual é o estádio do Barcelona?", opts: ["Camp Nou", "Bernabéu", "Wanda Metropolitano"], ans: "Camp Nou" },
        { q: "Quem é o técnico português que venceu a Champions com o Porto e a Inter?", opts: ["José Mourinho", "André Villas-Boas", "Fernando Santos"], ans: "José Mourinho" },
        { q: "Quem marcou o gol do título do Real Madrid na final de 2014?", opts: ["Sergio Ramos", "Bale", "Cristiano Ronaldo"], ans: "Sergio Ramos" },
        { q: "Qual é o clássico mais famoso da Inglaterra?", opts: ["Liverpool x Manchester United", "Arsenal x Tottenham", "Chelsea x Arsenal"], ans: "Liverpool x Manchester United" },
        { q: "Qual clube francês tem o apelido 'Les Parisiens'?", opts: ["PSG", "Lyon", "Marseille"], ans: "PSG" },
        { q: "Quem foi o capitão do Chelsea no título de 2012 da Champions?", opts: ["John Terry", "Frank Lampard", "Didier Drogba"], ans: "John Terry" },
        { q: "Qual clube italiano é conhecido como 'A Velha Senhora'?", opts: ["Juventus", "Milan", "Roma"], ans: "Juventus" },
        { q: "Qual país sediou a Eurocopa 2020?", opts: ["Vários países", "Inglaterra", "Alemanha"], ans: "Vários países" },
        { q: "Quem venceu a Champions League 2022-23?", opts: ["Manchester City", "Real Madrid", "Inter de Milão"], ans: "Manchester City" },
        { q: "Qual clube é o maior rival do Benfica?", opts: ["Porto", "Sporting", "Braga"], ans: "Sporting" },
        { q: "Quem marcou o gol do título do Chelsea em 2012?", opts: ["Didier Drogba", "Torres", "Lampard"], ans: "Didier Drogba" },
        { q: "Em que estádio o Real Madrid manda seus jogos?", opts: ["Santiago Bernabéu", "Metropolitano", "Camp Nou"], ans: "Santiago Bernabéu" },
        { q: "Qual foi o resultado da final da Euro 2016?", opts: ["Portugal 1x0 França", "França 1x0 Portugal", "Empate 0x0"], ans: "Portugal 1x0 França" },
        { q: "Quem é o maior artilheiro da seleção francesa?", opts: ["Giroud", "Henry", "Mbappé"], ans: "Giroud" },
        { q: "Qual time inglês tem o apelido 'The Blues'?", opts: ["Chelsea", "Manchester City", "Everton"], ans: "Chelsea" },
        { q: "Em que cidade fica o estádio San Siro?", opts: ["Milão", "Turim", "Roma"], ans: "Milão" },
        { q: "Quem é o maior rival do Real Madrid?", opts: ["Barcelona", "Atlético de Madrid", "Valencia"], ans: "Barcelona" },
        { q: "Qual jogador fez o gol do título da Champions 2021?", opts: ["Kai Havertz", "Mahrez", "Foden"], ans: "Kai Havertz" },
        { q: "Qual seleção venceu a Euro 2020?", opts: ["Itália", "Inglaterra", "Espanha"], ans: "Itália" },
        { q: "Qual clube espanhol é apelidado de 'Los Colchoneros'?", opts: ["Atlético de Madrid", "Sevilla", "Valencia"], ans: "Atlético de Madrid" },
        { q: "Quem é o artilheiro histórico da Premier League?", opts: ["Alan Shearer", "Wayne Rooney", "Harry Kane"], ans: "Alan Shearer" },
        { q: "Qual técnico levou o Liverpool ao título da Champions 2019?", opts: ["Jürgen Klopp", "Pep Guardiola", "Tuchel"], ans: "Jürgen Klopp" },
        { q: "Quem venceu a Champions de 2013?", opts: ["Bayern de Munique", "Dortmund", "Chelsea"], ans: "Bayern de Munique" },
        { q: "Qual clube francês venceu a Champions em 1993?", opts: ["Marseille", "PSG", "Lyon"], ans: "Marseille" },
        { q: "Quem é o artilheiro histórico do Real Madrid?", opts: ["Cristiano Ronaldo", "Raúl", "Benzema"], ans: "Cristiano Ronaldo" },
        { q: "Qual clube tem o apelido 'The Gunners'?", opts: ["Arsenal", "Tottenham", "West Ham"], ans: "Arsenal" },
        { q: "Em qual estádio o Bayern de Munique manda seus jogos?", opts: ["Allianz Arena", "Signal Iduna Park", "Olympiastadion"], ans: "Allianz Arena" },
        { q: "Qual é o rival do Fenerbahçe na Turquia?", opts: ["Galatasaray", "Besiktas", "Trabzonspor"], ans: "Galatasaray" },
        { q: "Qual jogador ganhou a Bola de Ouro em 2022?", opts: ["Benzema", "Messi", "Mbappé"], ans: "Benzema" },
        { q: "Quem é o maior rival do Arsenal?", opts: ["Tottenham", "Chelsea", "West Ham"], ans: "Tottenham" },
        { q: "Qual seleção venceu a Copa de 2018?", opts: ["França", "Croácia", "Alemanha"], ans: "França" },
        { q: "Quem é o técnico atual do Manchester City (2025)?", opts: ["Pep Guardiola", "Arteta", "Ten Hag"], ans: "Pep Guardiola" },
        { q: "Em que cidade fica o estádio Old Trafford?", opts: ["Manchester", "Londres", "Liverpool"], ans: "Manchester" },
        { q: "Qual é o clássico de Lisboa?", opts: ["Benfica x Sporting", "Benfica x Porto", "Sporting x Braga"], ans: "Benfica x Sporting" },
        { q: "Quem foi o craque da Euro 2021?", opts: ["Donnarumma", "Kane", "Mbappé"], ans: "Donnarumma" },
        { q: "Qual clube venceu mais títulos da Premier League?", opts: ["Manchester United", "Liverpool", "Arsenal"], ans: "Manchester United" },
        { q: "Qual é o estádio do Olympique de Marseille?", opts: ["Velodrome", "Parc des Princes", "Stade de France"], ans: "Velodrome" },
        { q: "Quem é o rival histórico do Sevilla?", opts: ["Real Betis", "Valencia", "Villarreal"], ans: "Real Betis" },
        { q: "Qual país tem o maior número de títulos da Euro?", opts: ["Alemanha", "Espanha", "Itália"], ans: "Alemanha" },
        { q: "Qual jogador é conhecido como 'O Faraó'?", opts: ["Mohamed Salah", "Mahrez", "Hakimi"], ans: "Mohamed Salah" },
        { q: "Qual seleção perdeu a final da Euro 2020 nos pênaltis?", opts: ["Inglaterra", "Itália", "Dinamarca"], ans: "Inglaterra" },
        { q: "Quem é o rival do PSV na Holanda?", opts: ["Ajax", "Feyenoord", "AZ Alkmaar"], ans: "Ajax" },
        { q: "Qual time escocês tem mais títulos nacionais?", opts: ["Rangers", "Celtic", "Aberdeen"], ans: "Rangers" },
            { q: "Quem venceu a Bola de Ouro de 2023?", opts: ["Messi", "Haaland", "Mbappé"], ans: "Messi" },
            { q: "Quem ganhou o prêmio Golden Boy em 2022?", opts: ["Gavi", "Pedri", "Bellingham"], ans: "Gavi" },
            { q: "Qual jogador brasileiro já venceu o prêmio Puskás duas vezes?", opts: ["Neymar", "Cristiano Ronaldo", "James Rodríguez"], ans: "Neymar" },
            { q: "Quem foi o artilheiro da Copa do Mundo de 2022?", opts: ["Mbappé", "Messi", "Giroud"], ans: "Mbappé" },
            { q: "Qual time venceu a Libertadores 2023?", opts: ["Fluminense", "Palmeiras", "Boca Juniors"], ans: "Fluminense" },
            { q: "Qual jogador ganhou o prêmio The Best da FIFA em 2022?", opts: ["Messi", "Benzema", "Lewandowski"], ans: "Messi" },
            { q: "Quem venceu o Puskás Award em 2020?", opts: ["Son Heung-min", "Zlatan Ibrahimović", "Giroud"], ans: "Son Heung-min" },
            { q: "Qual país venceu a Copa América de 2021?", opts: ["Argentina", "Brasil", "Uruguai"], ans: "Argentina" },
            { q: "Quem venceu a Eurocopa 2016?", opts: ["Portugal", "França", "Alemanha"], ans: "Portugal" },
            { q: "Qual é o maior campeão da Copa do Mundo?", opts: ["Brasil", "Alemanha", "Itália"], ans: "Brasil" },
            { q: "Quem foi o técnico da França na Copa de 2022?", opts: ["Didier Deschamps", "Laurent Blanc", "Zidane"], ans: "Didier Deschamps" },
            { q: "Qual jogador ganhou a Bola de Ouro da Copa 2014?", opts: ["Messi", "James Rodríguez", "Neymar"], ans: "Messi" },
            { q: "Quem venceu o prêmio Golden Boy em 2023?", opts: ["Bellingham", "Musiala", "Gavi"], ans: "Bellingham" },
            { q: "Qual clube francês venceu mais títulos da Ligue 1?", opts: ["PSG", "Saint-Étienne", "Lyon"], ans: "PSG" },
            { q: "Qual time inglês venceu a Premier League 2023/24?", opts: ["Manchester City", "Arsenal", "Liverpool"], ans: "Manchester City" },
            { q: "Qual é o clube com mais títulos da Bundesliga?", opts: ["Bayern de Munique", "Dortmund", "Hamburgo"], ans: "Bayern de Munique" },
            { q: "Quem venceu o prêmio Puskás de 2011?", opts: ["Neymar", "Rooney", "Messi"], ans: "Neymar" },
            { q: "Qual seleção venceu a Copa América de 2019?", opts: ["Brasil", "Argentina", "Chile"], ans: "Brasil" },
            { q: "Quem foi o melhor jogador da Champions 2022/23?", opts: ["Rodri", "Haaland", "De Bruyne"], ans: "Rodri" },
            { q: "Qual time argentino tem o apelido 'Los Millonarios'?", opts: ["River Plate", "Boca Juniors", "Independiente"], ans: "River Plate" },
            { q: "Quem venceu a Bola de Ouro em 2018?", opts: ["Modric", "Ronaldo", "Griezmann"], ans: "Modric" },
            { q: "Quem foi o artilheiro da Champions 2022/23?", opts: ["Haaland", "Vinícius Júnior", "Mbappé"], ans: "Haaland" },
            { q: "Qual seleção venceu a Copa do Mundo de 2010?", opts: ["Espanha", "Holanda", "Alemanha"], ans: "Espanha" },
            { q: "Quem foi o técnico campeão da Libertadores 2022?", opts: ["Abel Ferreira", "Cuca", "Gallardo"], ans: "Abel Ferreira" },
            { q: "Qual jogador argentino venceu o Golden Boy em 2020?", opts: ["Ansu Fati", "Lautaro Martínez", "Messi"], ans: "Ansu Fati" },
            { q: "Quem foi eleito melhor jogador jovem da Copa 2022?", opts: ["Enzo Fernández", "Bellingham", "Gavi"], ans: "Enzo Fernández" },
            { q: "Qual time espanhol venceu a Europa League 2022/23?", opts: ["Sevilla", "Roma", "Juventus"], ans: "Sevilla" },
            { q: "Quem marcou o gol do título do Mundial de Clubes 2022?", opts: ["Vinícius Júnior", "Benzema", "Rodrygo"], ans: "Vinícius Júnior" },
            { q: "Qual clube brasileiro foi vice da Libertadores 2023?", opts: ["Boca Juniors", "Palmeiras", "Fluminense"], ans: "Boca Juniors" },
            { q: "Quem foi eleito o melhor goleiro do mundo em 2023?", opts: ["Emiliano Martínez", "Courtois", "Ederson"], ans: "Emiliano Martínez" },
            { q: "Qual clube inglês venceu a Champions de 2021?", opts: ["Chelsea", "City", "Liverpool"], ans: "Chelsea" },
            { q: "Quem é o maior artilheiro da seleção argentina?", opts: ["Messi", "Batistuta", "Agüero"], ans: "Messi" },
            { q: "Qual jogador venceu o Puskás 2023?", opts: ["Guilherme Madruga", "Vinícius Júnior", "Rodrygo"], ans: "Guilherme Madruga" },
            { q: "Qual técnico levou o Flamengo ao Mundial de 2019?", opts: ["Jorge Jesus", "Dorival Júnior", "Abel Braga"], ans: "Jorge Jesus" },
            { q: "Quem foi o melhor jogador da Copa do Mundo 2022?", opts: ["Messi", "Mbappé", "Modric"], ans: "Messi" },
            { q: "Qual time francês revelou Mbappé?", opts: ["Monaco", "PSG", "Lyon"], ans: "Monaco" },
            { q: "Quem é o capitão do Real Madrid em 2025?", opts: ["Nacho", "Modric", "Carvajal"], ans: "Nacho" },
            { q: "Qual é o rival histórico do Manchester United?", opts: ["Liverpool", "City", "Leeds"], ans: "Liverpool" },
            { q: "Quem venceu a Copa do Rei 2023/24?", opts: ["Athletic Bilbao", "Real Madrid", "Barcelona"], ans: "Athletic Bilbao" },
            { q: "Qual clube alemão revelou Thomas Müller?", opts: ["Bayern de Munique", "Stuttgart", "Dortmund"], ans: "Bayern de Munique" },
            { q: "Quem é o maior artilheiro da seleção inglesa?", opts: ["Harry Kane", "Rooney", "Lineker"], ans: "Harry Kane" },
            { q: "Qual seleção venceu a Copa América 2024?", opts: ["Argentina", "Brasil", "Uruguai"], ans: "Argentina" },
            { q: "Quem ganhou o prêmio Golden Boy 2021?", opts: ["Pedri", "Bellingham", "Musiala"], ans: "Pedri" },
            { q: "Qual time inglês revelou Marcus Rashford?", opts: ["Manchester United", "City", "Liverpool"], ans: "Manchester United" },
            { q: "Qual jogador venceu a Bola de Ouro de 2015?", opts: ["Messi", "Ronaldo", "Neymar"], ans: "Messi" },
            { q: "Quem marcou o gol mais bonito da Copa 2014 (Puskás)?", opts: ["James Rodríguez", "Van Persie", "Robben"], ans: "James Rodríguez" },
            { q: "Qual é o estádio do PSG?", opts: ["Parc des Princes", "Velodrome", "Stade de France"], ans: "Parc des Princes" },
            { q: "Quem foi o melhor técnico da temporada 2022/23?", opts: ["Pep Guardiola", "Carlo Ancelotti", "Simone Inzaghi"], ans: "Pep Guardiola" },
            { q: "Quem venceu a Supercopa da UEFA 2023?", opts: ["Manchester City", "Sevilla", "Real Madrid"], ans: "Manchester City" },
            { q: "Qual clube argentino tem o apelido 'La Academia'?", opts: ["Racing", "Boca Juniors", "River Plate"], ans: "Racing" },
            { q: "Qual jogador venceu o prêmio Kopa Trophy em 2023?", opts: ["Bellingham", "Pedri", "Musiala"], ans: "Bellingham" },
            { q: "Quem foi o craque da Libertadores 2023?", opts: ["Germán Cano", "Arias", "André"], ans: "Germán Cano" },
                { q: "Quem foi o capitão da Costa do Marfim na Copa de 2010?", opts: ["Didier Drogba", "Yaya Touré", "Kolo Touré"], ans: "Didier Drogba" },
                { q: "Qual atacante ganês foi destaque na Copa do Mundo de 2010?", opts: ["Asamoah Gyan", "Kevin-Prince Boateng", "Muntari"], ans: "Asamoah Gyan" },
                { q: "Quem marcou o gol do título da Champions 2012 para o Chelsea?", opts: ["Didier Drogba", "Lampard", "Torres"], ans: "Didier Drogba" },
                { q: "Qual jogador nigeriano venceu a Liga dos Campeões de 2012 pelo Chelsea?", opts: ["Mikel", "Moses", "Essien"], ans: "Mikel" },
                { q: "Qual jogador francês negro foi destaque da Juventus entre 2013 e 2015?", opts: ["Paul Pogba", "Evra", "Coman"], ans: "Paul Pogba" },
                { q: "Qual jogador ganês jogou pelo Milan em 2011 e era conhecido pelas danças nas comemorações?", opts: ["Kevin-Prince Boateng", "Essien", "Asamoah"], ans: "Kevin-Prince Boateng" },
                { q: "Qual jogador camaronês teve passagem pelo Barcelona e Inter, sendo multicampeão?", opts: ["Samuel Eto'o", "Alex Song", "Geremi"], ans: "Samuel Eto'o" },
                { q: "Quem era o principal atacante do Arsenal entre 2008 e 2011?", opts: ["Van Persie", "Adebayor", "Walcott"], ans: "Adebayor" },
                { q: "Qual jogador francês negro foi revelado pelo Lyon e brilhou no Real Madrid?", opts: ["Benzema", "Malouda", "Diarra"], ans: "Benzema" },
                { q: "Quem foi o lateral-esquerdo brasileiro que brilhou no Real Madrid entre 2008 e 2015?", opts: ["Marcelo", "Roberto Carlos", "Maxwell"], ans: "Marcelo" },
                { q: "Qual jogador senegalês jogou no Newcastle e ficou famoso por seu carisma e gols decisivos?", opts: ["Demba Ba", "Cissé", "Niang"], ans: "Demba Ba" },
                { q: "Quem foi o zagueiro brasileiro que era capitão do PSG em 2013?", opts: ["Thiago Silva", "Marquinhos", "Alex"], ans: "Thiago Silva" },
                { q: "Qual jogador africano foi artilheiro da Copa Africana de Nações 2012?", opts: ["Didier Drogba", "Emenike", "Manucho"], ans: "Emenike" },
                { q: "Qual atacante nigeriano jogou pelo CSKA Moscou e se destacou na Copa de 2014?", opts: ["Ahmed Musa", "Moses", "Obi Mikel"], ans: "Ahmed Musa" },
                { q: "Quem era o craque da seleção da Gana na Copa de 2014?", opts: ["Asamoah Gyan", "Ayew", "Boateng"], ans: "Asamoah Gyan" },
                { q: "Qual jogador brasileiro negro era conhecido como 'Imperador'?", opts: ["Adriano", "Ronaldo", "Robinho"], ans: "Adriano" },
                { q: "Quem foi o atacante negro do Manchester United entre 2012 e 2015?", opts: ["Danny Welbeck", "Lingard", "Nani"], ans: "Danny Welbeck" },
                { q: "Qual jogador português de origem cabo-verdiana brilhou no Manchester United?", opts: ["Nani", "Ronaldo", "Anderson"], ans: "Nani" },
                { q: "Qual promissor jogador belga estreou no Chelsea em 2012?", opts: ["Eden Hazard", "De Bruyne", "Lukaku"], ans: "Eden Hazard" },
                { q: "Quem era o centroavante da seleção belga em 2014?", opts: ["Lukaku", "Benteke", "Origi"], ans: "Lukaku" },
                { q: "Qual jogador brasileiro negro era lateral do Barcelona e da Seleção?", opts: ["Dani Alves", "Maicon", "Rafinha"], ans: "Dani Alves" },
                { q: "Quem foi o volante francês de destaque do Real Madrid entre 2010 e 2013?", opts: ["Lass Diarra", "Makelele", "Kanté"], ans: "Lass Diarra" },
                { q: "Qual jogador negro francês brilhou no Bayern entre 2010 e 2014?", opts: ["Franck Ribéry", "Coman", "Evra"], ans: "Franck Ribéry" },
                { q: "Quem foi o goleiro da Nigéria na Copa de 2014?", opts: ["Vincent Enyeama", "Ikeme", "Okoye"], ans: "Vincent Enyeama" },
                { q: "Qual jogador japonês se destacou no CSKA Moscou e no Milan?", opts: ["Keisuke Honda", "Kagawa", "Okazaki"], ans: "Keisuke Honda" },
                { q: "Qual clube japonês revelou Shinji Kagawa?", opts: ["Cerezo Osaka", "Urawa Reds", "Kashima Antlers"], ans: "Cerezo Osaka" },
                { q: "Qual seleção asiática chegou às quartas de final da Copa de 2011?", opts: ["Japão", "Coreia do Sul", "Austrália"], ans: "Japão" },
                { q: "Quem foi o camisa 10 da Coreia do Sul na Copa de 2010?", opts: ["Park Ji-sung", "Son Heung-min", "Lee Chung-yong"], ans: "Park Ji-sung" },
                { q: "Qual time asiático venceu a Copa da Ásia de 2011?", opts: ["Japão", "Irã", "Austrália"], ans: "Japão" },
                { q: "Qual atacante argelino brilhou no Leicester em 2014/15?", opts: ["Riyad Mahrez", "Slimani", "Feghouli"], ans: "Riyad Mahrez" },
                { q: "Quem foi o volante africano destaque do Manchester City em 2014?", opts: ["Yaya Touré", "Fernandinho", "Kanté"], ans: "Yaya Touré" },
                { q: "Qual jogador marfinense jogou no Galatasaray em 2013?", opts: ["Didier Drogba", "Gervinho", "Zokora"], ans: "Didier Drogba" },
                { q: "Quem era o técnico da seleção japonesa em 2014?", opts: ["Alberto Zaccheroni", "Okada", "Halilhodžić"], ans: "Alberto Zaccheroni" },
                { q: "Qual jogador brasileiro despontava como promessa no Santos em 2010?", opts: ["Neymar", "Ganso", "André"], ans: "Neymar" },
                { q: "Quem foi o atacante jovem do Milan em 2013 conhecido pelo temperamento forte?", opts: ["Balotelli", "Pato", "Niang"], ans: "Balotelli" },
                { q: "Qual meia africano jogava no Chelsea e era conhecido pela força física?", opts: ["Essien", "Mikel", "Obi"], ans: "Essien" },
                { q: "Qual jogador nigeriano atuou como ponta no Liverpool entre 2010 e 2013?", opts: ["Victor Moses", "Ibe", "Babajide"], ans: "Victor Moses" },
                { q: "Qual atacante brasileiro foi destaque no Shakhtar Donetsk em 2012?", opts: ["Willian", "Douglas Costa", "Luiz Adriano"], ans: "Luiz Adriano" },
                { q: "Quem foi o goleiro titular do Japão na Copa de 2014?", opts: ["Kawashima", "Nishikawa", "Gonda"], ans: "Kawashima" },
                { q: "Qual time asiático contratou Diego Forlán em 2014?", opts: ["Cerezo Osaka", "Al Sadd", "FC Tokyo"], ans: "Cerezo Osaka" },
                { q: "Qual jogador brasileiro negro jogou no Milan e PSG nesse período?", opts: ["Alex", "Thiago Silva", "David Luiz"], ans: "Thiago Silva" },
                { q: "Quem foi o melhor jogador asiático de 2012 segundo a AFC?", opts: ["Lee Keun-ho", "Honda", "Son Heung-min"], ans: "Lee Keun-ho" },
                { q: "Qual promissor atacante jogava no Basel antes de ir para o Chelsea em 2013?", opts: ["Salah", "Shaqiri", "Elneny"], ans: "Salah" },
                { q: "Qual jogador brasileiro foi eleito o melhor do Mundial Sub-20 de 2011?", opts: ["Oscar", "Neymar", "Lucas Moura"], ans: "Oscar" },
                { q: "Quem era o camisa 10 da Nigéria nas Olimpíadas de 2008?", opts: ["Obi Mikel", "Martins", "Yakubu"], ans: "Obi Mikel" },
                { q: "Qual atacante africano jogou no Sunderland e era conhecido pelo físico?", opts: ["Asamoah Gyan", "Anichebe", "Moses"], ans: "Asamoah Gyan" },
                { q: "Quem foi o meia japonês destaque do Borussia Dortmund em 2012?", opts: ["Kagawa", "Honda", "Okazaki"], ans: "Kagawa" },
                { q: "Qual jogador brasileiro negro era reserva de Marcelo no Real Madrid em 2013?", opts: ["Coentrão", "Marcelo Vieira", "Danilo"], ans: "Coentrão" },
                { q: "Quem foi o atacante africano campeão da Champions com o Barcelona em 2009?", opts: ["Eto’o", "Touré", "Keita"], ans: "Eto’o" },
                { q: "Qual jogador africano marcou na final do Mundial de Clubes 2010?", opts: ["Samuel Eto’o", "Kalou", "Muntari"], ans: "Samuel Eto’o" }
                
    ];
    // --- Funções utilitárias --
    function shuffleArray(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    }

    function pickRandomQuestions(quiz, n = 18) {
        shuffleArray(quiz);
        return quiz.slice(0, n);
    }

    // Pega 15 perguntas aleatórias
    let questions = pickRandomQuestions(Quiz, 18);

    let current = 0;
    let score = 0;
    let timer;
    let time = 12;

    function loadQuestion() {
        if (current >= questions.length) {
            endQuiz();
            return;
        }
    
        const question = questions[current];
    
        // Mostra contador de perguntas
        $("#question").text(`Pergunta ${current + 1} de ${questions.length}: ${question.q}`);
        $("#options").empty();
    
        question.opts.forEach(opt => {
            const btn = $("<button>").text(opt);
            btn.click(() => checkAnswer(opt));
            $("#options").append(btn);
        });
    
        time = 12;
        $("#timer").text(time);
        clearInterval(timer);
        timer = setInterval(updateTimer, 1000);
    }
    
    function updateTimer() {
        time--;
        $("#timer").text(time);
        if (time <= 0) {
            clearInterval(timer);
            current++;
            loadQuestion();
        }
    }

    function checkAnswer(choice) {
        const question = questions[current];
        if (choice === question.ans) score++;
        current++;
        clearInterval(timer);
        loadQuestion();
    }

    function endQuiz() {
        clearInterval(timer);
        $("#options").empty();
        $(".timer").hide();
        $("#question").text("🏁 Fim do Quiz!");
        $("#result").text(`Você acertou ${score} de ${questions.length} perguntas.`);
        $("#restart-btn").show();
    }

    $("#restart-btn").click(function() {
        current = 0;
        score = 0;
        $(".timer").show();
        $("#restart-btn").hide();
        $("#result").text("");
        questions = pickRandomQuestions(Quiz, 15);
        loadQuestion();
    });

    loadQuestion();
});
